#!/bin/bash
#BROKEN! can't login to set, not sure why, no error, but no cookie returned. so use windows login and copy cookie here for now
echo "SERVER ${SET_SERVER}"
echo "USERNAME ${SET_USERNAME}"
echo "BROKER_CODE ${SET_BROKER_CODE}"
DAT="txtLogin=${SET_USERNAME}&txtPassword=${SET_PASSWORD}&txtBrokerId=${SET_BROKER_CODE}&txtRole=&txtDefaultPage=&txtSecureKey=NONE&txtLanguage=English&txtUserClass=&txtLoginPage=tisco2%2Fpre_logged_in%2Fpage%2Flogin.jsp&txtService=&txtSystem=&txtRealRole=INTERNET&txtLoginType=&txtSessionId=&txtJSSupport=&txtMaintenanceLogin=&txtSTTLogin=${SET_USERNAME}&txtDefaultCentralServer=wwwa1.settrade.com&txtAccountNo=&txtUserName=${SET_USERNAME}&txtLoginFailed=&txtUKey=${SET_USERNAME}_${SET_BROKER_CODE}"
echo $DAT
export HEADER='-H "Origin: https://${SET_SERVER}" -H "Accept-Encoding: gzip, deflate, br" -H "Accept-Language: en-US,en;q=0.8" -H "Upgrade-Insecure-Requests: 1" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36" -H "Content-Type: application/x-www-form-urlencoded" -H "Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8" -H "Cache-Control: max-age=0" -H "Referer: https://${SET_SERVER}/LoginRepOnRole.jsp" -H "Connection: keep-alive"'
#rm -f cookie2.txt
curl -s -b cookie.txt -c cookie.txt "https://${SET_SERVER}/LoginBySystem.jsp" $HEADER --data "$DAT"

#expect this kind of cookie
# Netscape HTTP Cookie File
# https://curl.haxx.se/docs/http-cookies.html
# This file was generated by libcurl! Edit at your own risk.

#wen066.settrade.com	FALSE	/	TRUE	0	JSESSIONID	5E8BE8EBF6A38912A351AAE9A37664C8.ITPPN-TCE-A175
#.settrade.com	TRUE	/	FALSE	0	__txtUTID	1530146062758b2299475-dfd7-436c-9a6e-ddadd44f6703
#.settrade.com	TRUE	/	FALSE	0	__txtUKey	<username_brokercode>
#.settrade.com	TRUE	/	TRUE	1530146123	qtp	0
#.settrade.com	TRUE	/	TRUE	0	if	"15vRZeOdmlNdGo245fweYShMvoH8gIPt1t5QfJD7UIU1arzgsmfRdODVTBMQtouX6qjMITTkJVohOYpQIpqozlBO7Hq/mo1a0ja6tLkzBPs="
#.settrade.com	TRUE	/	TRUE	0	st	"ITP|10.33.1.175|1530146063000|/LoginBySystem.jsp"
#.settrade.com	TRUE	/	TRUE	0	tm	""
#.settrade.com	TRUE	/	TRUE	0	id	05kH3QO9fbkL3QR4PpNOmA0000000000
#.settrade.com	TRUE	/	TRUE	0	rl	"qv6vTcHevm5iK+3b1plSGEQuo/nO5/+Rqao0Lg=="
#.settrade.com	TRUE	/	TRUE	0	xid	D79BD146E39D9A535D1A8DB8
